### ISSUE TITLE
Multiple issues with deleting episode files

### ISSUE THREAD

**Issue by PieterBoeren** [Hertizch/SonarrSharp#3]
1. When deleting an episode file, the code is throwing an exception when setting the content type (SonarrClient.cs ~ 385). Probably all delete methods fail because of this (same for issue below).
2. After you remove that particular line code, the api call is not correct. The "/api" is removed from the url. I can't find it at the moment, but I read somewhere on MSDN that the baseAddress should end with a "/" (so, ".../api/").
3. HttpClient itself shouldn't be disposed (see: https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/)

**Comment by Hertizch** [comment]
I'll have a look later today. It was working when I wrote it but maybe something has changed..

**Comment by PieterBoeren** [comment]
And I forgot: if the delete call throws an error (like forbidden for example), you'll never see this unless you use a tool like Fiddler to intercept the calls.

**Comment by Hertizch** [comment]
This issue should now be fixed. I was using BaseAddress wrong so the entire api url did not get passed, as well as a header that was not needed.
